# Generated by Django 4.1 on 2022-08-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('nationality', models.CharField(choices=[('KZ', 'Kazakhstan'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('CH', 'China'), ('IL', 'Israel'), ('FR', 'France'), ('DE', 'Germany'), ('FL', 'Finland'), ('SE', 'Swedish'), ('PL', 'Poland'), ('BG', 'Bulgaria')], max_length=2)),
                ('birthdate', models.DateField()),
                ('current_role', models.CharField(choices=[('1', 'Carry'), ('2', 'Midline'), ('3', 'Offliner'), ('4', 'SemiSupport'), ('5', 'Support')], max_length=1)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team')),
            ],
        ),
    ]
