# Generated by Django 4.1 on 2022-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_approx_total_winnings_alter_player_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_role',
            field=models.CharField(choices=[('1', 'Carry'), ('2', 'Midline'), ('3', 'Offliner'), ('4', 'SemiSupport'), ('5', 'Support'), ('6', 'Coach')], max_length=1),
        ),
    ]
