# Generated by Django 4.1 on 2022-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('EEU', 'East Europe'), ('WEU', 'West Europe'), ('SA', 'South America'), ('NA', 'North America'), ('CH', 'China'), ('SEA', 'Southeast Asia')], max_length=3)),
                ('tier_level', models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], max_length=1)),
            ],
        ),
    ]
