# Generated by Django 4.1 on 2022-08-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourname', models.CharField(max_length=60)),
                ('organizer', models.CharField(max_length=60)),
                ('tournament_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=7)),
                ('prize_pool', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tier_level', models.CharField(choices=[('1', 'Tier 1'), ('2', 'Tier 2'), ('3', 'Tier 3')], max_length=1)),
                ('participants', models.ManyToManyField(to='team.team')),
            ],
        ),
    ]
