# Generated by Django 4.1 on 2022-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourname',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
