# Generated by Django 4.1 on 2022-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourname', '0002_tourname_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourname',
            name='participants_number',
            field=models.IntegerField(default=0),
        ),
    ]
